name: acko_flutter_example
description: Preview app for the acko_flutter design system package.
publish_to: none
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  acko_flutter:
    path: ..
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
